---
config:
  send_anonymous_usage_stats: false
engagement_survey:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ./dbt.duckdb
    prod:
      type: duckdb
      path: ./dbt-prod.duckdbl

